function cfg = path_config_template()
% Copy this file to user_paths.m and edit for your machine.

cfg = struct();

% Root directories
cfg.project_root = '/path/to/striatal-state-dynamics-pipeline';
cfg.data_root    = '/path/to/data';
cfg.results_root = '/path/to/results';   % optional legacy field
cfg.output_root  = '/path/to/outputs';   % recommended root for all generated outputs

% MATLAB dependencies
cfg.toolbox.efc   = '/path/to/eFC/fcn';
cfg.toolbox.nifti = '/path/to/NIfTI_20140122';
cfg.toolbox.bct   = '/path/to/BCT';

% Shared resources
cfg.mask_path = '/path/to/DiscoveryReplication_rStriatum_Intersect_Tightened.nii.gz';
cfg.nifti_img_root = '/path/to/nifti/export/root';

% Template / standardization files
cfg.template.reference = '/path/to/efc_reference_template.mat';
cfg.rest_params_file   = '/path/to/rest_standardization_params.mat';


% Spreadsheet / behavioral metadata
cfg.subject_vars_file = '/path/to/Gambling_Subject_Vars_n407.xlsx';

% Timing files
cfg.timing.win_rl  = '/path/to/win.txt';
cfg.timing.loss_rl = '/path/to/loss.txt';
cfg.timing.win_lr  = '/path/to/win_LR.txt';
cfg.timing.loss_lr = '/path/to/loss_LR.txt';

% Run-specific settings. Populate for every run you plan to analyze.
% Required fields for the core script:
%   striatal_dir, cortical_dir, trs, subjects, dataset_type
% Optional:
%   output_dir, save_path, export_dir, nifti_out_dir, results_file
cfg.runs.REST1_LR = struct( ...
    'striatal_dir', '/path/to/STRIATAL_REST1_LR', ...
    'cortical_dir', '/path/to/CORTICAL_REST1_LR', ...
    'trs', 1200, ...
    'subjects', 407, ...
    'dataset_type', 'rest', ...
    'results_file', '/path/to/results/REST1_LR/efc_states_louvain_all_detectors.mat');

cfg.runs.REST1_RL = struct( ...
    'striatal_dir', '/path/to/STRIATAL_REST1_RL', ...
    'cortical_dir', '/path/to/CORTICAL_REST1_RL', ...
    'trs', 1200, ...
    'subjects', 407, ...
    'dataset_type', 'rest', ...
    'results_file', '/path/to/results/REST1_RL/efc_states_louvain_all_detectors.mat');

cfg.runs.REST2_LR = struct( ...
    'striatal_dir', '/path/to/STRIATAL_REST2_LR', ...
    'cortical_dir', '/path/to/CORTICAL_REST2_LR', ...
    'trs', 1200, ...
    'subjects', 407, ...
    'dataset_type', 'rest', ...
    'results_file', '/path/to/results/REST2_LR/efc_states_louvain_all_detectors.mat');

cfg.runs.REST2_RL = struct( ...
    'striatal_dir', '/path/to/STRIATAL_REST2_RL', ...
    'cortical_dir', '/path/to/CORTICAL_REST2_RL', ...
    'trs', 1200, ...
    'subjects', 407, ...
    'dataset_type', 'rest', ...
    'results_file', '/path/to/results/REST2_RL/efc_states_louvain_all_detectors.mat');

cfg.runs.GAMBLING_RL = struct( ...
    'striatal_dir', '/path/to/STRIATAL_GAMBLING_RL', ...
    'cortical_dir', '/path/to/CORTICAL_GAMBLING_RL', ...
    'trs', 253, ...
    'subjects', 407, ...
    'dataset_type', 'task', ...
    'results_file', '/path/to/results/GAMBLING_RL/efc_states_louvain_all_detectors.mat');

cfg.runs.GAMBLING_LR = struct( ...
    'striatal_dir', '/path/to/STRIATAL_GAMBLING_LR', ...
    'cortical_dir', '/path/to/CORTICAL_GAMBLING_LR', ...
    'trs', 253, ...
    'subjects', 407, ...
    'dataset_type', 'task', ...
    'results_file', '/path/to/results/GAMBLING_LR/efc_states_louvain_all_detectors.mat');

end
